[tool.poetry]
name = "resumao"
version = "0.1.0"
description = ""
authors = ["larissa"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
